config/routes.rb
Tams::Application.routes.draw do
  

  devise_for :users # , :controllers => { :registrations => "users/registrations"}

  resources :users, :roles

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'roles#new' #'static_pages#about'

  match '/contact', to: 'roles#new' #'static_pages#contact'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)

    user ||= User.new # guest user

    if user.role? :''  #super_admin
      can :manage, :all
    elsif user.role? :Manager
      can :manage, [Product, Asset, Issue]
    elsif user.role? :suppervisor
      can :read, [Product, Asset] 
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
   has_and_belongs_to_many :roles


   def role?(role)
         return !!self.roles.find_by_name(role.to_s.camelize)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  #ensure authorization happens on every action
  #check_authorization

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def new
    @role = Role.new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    #@post = current_user.posts.build if signed_in?
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :check_permissions, :only => [:new, :create, :cancel]
  skip_before_filter :require_no_authentication

  def check_permissions
    authorize! :create, resource
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
  <nav>
    <ul>
      <li> <%= link_to "Manage Roles", roles_path %></li>
      <li><%= link_to "About", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
  <div class="container">
    <%= link_to "TAMS", root_path, id: "logo" %>
    <nav>
    <ul class="nav pull-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      
      <% if user_signed_in? %>
        <li id="fat-menu" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% current_user = "" %>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
          <%= link_to "Sign out",destroy_user_session_path , method: "delete" %>
          </li>
        </ul>
        </li>
      <%else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <%end %>
    </ul>
    </nav>
  </div>
</div>
</header>

app/views/layouts/_html5shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/html5shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/roles/create.html.erb
<h1>Roles#create</h1>
<p>Find me in app/views/roles/create.html.erb</p>

app/views/roles/destroy.html.erb
<h1>Roles#destroy</h1>
<p>Find me in app/views/roles/destroy.html.erb</p>

app/views/roles/edit.html.erb
<h1>Roles#edit</h1>
<p>Find me in app/views/roles/edit.html.erb</p>

app/views/roles/index.html.erb
<h1>Roles#index</h1>
 <nav>
    <ul>
      <li> <%= link_to "List Roles", roles_path %></li>
      <li><%= link_to "Manage Users role", help_path %></li>
      <li><%= link_to "Create", new_role_path %></li>
    </ul>
  </nav>
</footer>

app/views/roles/new.html.erb
<h1>Roles#new</h1>
<p>Find me in app/views/roles/new.html.erb</p>

app/views/roles/show.html.erb
<h1>Roles#show</h1>
<p>Find me in app/views/roles/show.html.erb</p>

app/views/roles/update.html.erb
<h1>Roles#update</h1>
<p>Find me in app/views/roles/update.html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
    <h1>About Us</h1>
    <p>
       <a href="http://tams.com">TAMS</a>
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
    <h1>Contact Us</h1>
    <p>
    </p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
    <h1>Help</h1>
    <p>
    </p>

app/views/static_pages/home.html.erb
<% if  user_signed_in? %>
  <div class="row">
    <aside class="span4">
    <section>
    </section>
    <section>
    </section>
    </aside>
  </div>  
<% else %>
  <div class="center hero-unit">
    <h1>Time and Attendance Management System </h1>

    <h2>
      This is the home page for the
    </h2>

    <%= link_to "Sign up now!", new_user_registration_path,
      class: "btn btn-large btn-primary" %>
    </div>

    <%= link_to image_tag("rails.png", alt: "Rails"), 'http://tams.com/' %>
  <% end %> 